### ISSUE TITLE
Error Train NLU model

### ISSUE THREAD

**Issue by sanyaade-machine-learning** [btotharye/mycroft-helper#1]
Good day to you all.

Please I need help. The automated ./setup.sh ran without any problems. Many thanks! 

But training the NLU model gave error as sown below:
Command: **python bot.py train-nlu**

**Console Error:**
> sanyaade@ns1:~/Applications/virtual-assistant/mycroft-helper$ python bot.py train-nlu
2018-07-08 14:47:38 INFO     rasa_nlu.training_data.loading  - Training data format of data/nlu_data.md is md
2018-07-08 14:47:38 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 68 (11 distinct intents)
	- Found intents: 'skills_list', 'goodbye', 'about_me', 'choose_os', 'docker_install', 'mycroft_help', 'mycroft_docs', 'thankyou', 'linux_install', 'pi_install', 'greet'
	- entity examples: 12 (1 distinct entities)
	- found entities: 'os'

Illegal instruction (core dumped)
sanyaade@ns1:~/Applications/virtual-assistant/mycroft-helper$ 

Please help!
Python: 3.6.0 ; Pip: 9.0.1 ; OS: Ubuntu 16.04

Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-machine-learning** [comment]
@btotharye : 

Yes I am using master branch,

I am running on Dell Server with 8 Cores, 32 gigabyte memory with Ubuntu 16.04
I cannot trace the "illegal instruction (core dumped) given as part of the error message.

I notice that there is no folder for model_directory e.g. ==> models/nlu', do I need to create this manually? Also ==>  fixed_model_name="current"

Many thanks for your support!

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by btotharye** [comment]
No you don't need to create anything manually the training commands will build that out, I just took this code and downloaded it and went through the install instructions and its working fine for me did you run the setup.sh file as well or at least make sure you have all the rasa dependencies?

```
$ python3 bot.py train-nlu
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2018-07-08 13:23:12 INFO     rasa_nlu.training_data.loading  - Training data format of data/nlu_data.md is md
2018-07-08 13:23:12 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
        - intent examples: 68 (11 distinct intents)
        - Found intents: 'skills_list', 'choose_os', 'goodbye', 'docker_install', 'mycroft_help', 'mycroft_docs', 'greet', 'thankyou', 'pi_install', 'linux_install', 'about_me'
        - entity examples: 12 (1 distinct entities)
        - found entities: 'os'

/home/btotharye/.local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-08 13:23:13 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2018-07-08 13:23:22 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-07-08 13:23:22 INFO     rasa_nlu.model  - Starting to train component nlp_spacy
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component tokenizer_spacy
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.                                                                                                                                
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component intent_featurizer_spacy                                                                                                         
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.                                                                                                                                
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component intent_entity_featurizer_regex
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component ner_crf
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component ner_synonyms
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Starting to train component intent_classifier_sklearn
Fitting 2 folds for each of 6 candidates, totalling 12 fits
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.1s finished
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-08 13:23:23 INFO     rasa_nlu.model  - Successfully saved model into '/home/btotharye/Downloads/mycroft-helper-master/models/nlu/default/current'

$ python3 bot.py train-dialogue
UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
/home/btotharye/.local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 7093.96it/s, # trackers=1]
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 943.24it/s, # trackers=15]
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 621.37it/s, # trackers=19]
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 615.32it/s, # trackers=18]
2018-07-08 13:24:01 INFO     rasa_core.featurizers  - Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer)...
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 692/692 [00:00<00:00, 3208.33it/s, # actions=421]
2018-07-08 13:24:01 INFO     rasa_core.featurizers  - Created 421 action examples.
Processed actions: 421it [00:00, 22598.79it/s, # examples=421]
2018-07-08 13:24:01 INFO     rasa_core.policies.memoization  - Memorized 421 unique action examples.
2018-07-08 13:24:01 INFO     rasa_core.featurizers  - Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer)...
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 692/692 [00:00<00:00, 3063.54it/s, # actions=1001]
2018-07-08 13:24:01 INFO     rasa_core.featurizers  - Created 1001 action examples.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
masking_1 (Masking)          (None, 5, 29)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                7936      
_________________________________________________________________
dense_1 (Dense)              (None, 14)                462       
_________________________________________________________________
activation_1 (Activation)    (None, 14)                0         
=================================================================
Total params: 8,398
Trainable params: 8,398
Non-trainable params: 0
_________________________________________________________________
2018-07-08 13:24:02 INFO     rasa_core.policies.keras_policy  - Fitting model with 1001 total samples and a validation split of 0.2
Train on 800 samples, validate on 201 samples
Epoch 1/400
2018-07-08 13:24:02.597655: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
800/800 [==============================] - 0s 455us/step - loss: 2.6439 - acc: 0.0937 - val_loss: 2.5941 - val_acc: 0.1194
...
...
Epoch 400/400 [==============================] - 0s 31us/step - loss: 0.0041 - acc: 1.0000 - val_loss: 0.0086 - val_acc: 0.9950
2018-07-08 13:24:12 INFO     rasa_core.policies.keras_policy  - Done fitting keras policy model
2018-07-08 13:24:13 INFO     rasa_core.agent  - Persisted model to '/home/btotharye/Downloads/mycroft-helper-master/models/dialogue'

$ python3 bot.py run
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
/home/btotharye/.local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-08 13:24:36 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/home/btotharye/.local/lib/python3.6/site-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/current/entity_synonyms.json'
  "".format(entity_synonyms_file))
Using TensorFlow backend.
2018-07-08 13:24:36.713082: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Bot loaded. Type a message and press enter: 
hello
/home/btotharye/.local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Hello, how may I help you?
1: Mycroft Help (/mycroft_help)
2: About Me (/about_me)
```

**Comment by sanyaade-machine-learning** [comment]
@btotharye : 
Good News: That train bug was TensorFlow bug see: https://github.com/tensorflow/tensorflow/issues/17411 

Having gone past train the model, I now have a new one that I think is MyCroft related:
Issuing command: python bot.py train-dialogue

Gave the following errors:

> Using TensorFlow backend.
Traceback (most recent call last):
  File "bot.py", line 35, in <module>
    class MycroftBot(object):
  File "bot.py", line 107, in MycroftBot
    train_dialogue()
  File "bot.py", line 46, in train_dialogue
    training_data = agent.load_data(training_data_file)
AttributeError: 'Agent' object has no attribute 'load_data'

Please help!

Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-machine-learning** [comment]
@btotharye : 
Okay I got it working.

Problem: Tensorflow AVX problems for my hardware 
Solution: build TensorFlow from source locally on my systems. 

This will detect my system type and will not enable AVX. Plus TensorFlow prompts you for other options as well.
After that, I was able to run the ./setup.sh, python bot.py train-nlu and python bot.py train-dialogue 
All went well. Also I was able to bump-up rasa_core  tensorflow==1.9.0rc0  **Note:** I could also build for 1.8.0 

See below output for my local test
> Using TensorFlow backend.
/home/sanyaade/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Bot loaded. Type a message and press enter: 
hello
/home/sanyaade/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Hello, how may I help you?
1: Mycroft Help (/mycroft_help)
2: About Me (/about_me)

I am now testing other Rasa samples, tutorials, rasa_nlu and other non-dockers for use.
Play more with mycroft-helper
Later I will give Articulate a spin for non docker installations.
I need to understand Rasa components by play with them.
The TensorFlow has taken me more than 3 weeks to solve

Many thanks for your help! :+1: 

God blesses!!!

Best regards,
Sanyaade

**Comment by btotharye** [comment]
Glad you got it working, I'm going to close this one out now
